const candy = [
  {
    name: "Twizzlers",
    category: "Chewy",
    price: 1.5,
    img: "https://www.ohnuts.com/noapp/showImage.cfm/zoom/_MG_55752.jpg",
    inStock: true,
  },
  {
    name: "Twix",
    category: "Chocolate",
    price: 2,
    img: "https://www.costco.co.uk/medias/sys_master/images/he9/h4c/64059407269918.jpg",
    inStock: true,
  },
  {
    name: "Jolly Ranchers",
    category: "Hard Candy",
    price: 2,
    img: "https://jcandy-weblinc.netdna-ssl.com/product_images/h1070033101-assorted-jolly-rancher-hard-candy/5cdfbc0b61707045890132f1/zoom.jpg?c=1558166540",
    inStock: false,
  },
  {
    name: "Dum-Dums",
    category: "Hard Candy",
    price: 0.5,
    img: "https://i0.wp.com/wertzcandies.com/wp-content/uploads/2017/08/DSC_8416-600-1.jpg?fit=600%2C600&ssl=1",
    inStock: true,
  },
  {
    name: "Snickers",
    category: "Chocolate",
    price: 1.5,
    img: "https://pyxis.nymag.com/v1/imgs/312/ee5/722453b0ee71b1400484caff77b2ece6d9-23-snickers-ice-cream-bars.rsquare.w700.jpg",
    inStock: false,
  },
  {
    name: "Sour Patch Kids",
    category: "Chewy",
    price: 1.25,
    img: "https://www.candywarehouse.com/item-images/128799-01_sour-patch-kids-candy-3-5lb-bag.jpg",
    inStock: false,
  },
  {
    name: "Swedish Fish",
    category: "Chewy",
    price: 1.25,
    img: "https://cdn.shopify.com/s/files/1/0557/6923/5628/products/1-KEN-074-2.jpg?v=1646072103",
    inStock: true,
  },
  {
    name: "Jawbreakers",
    category: "Hard Candy",
    price: 3,
    img: "https://www.mastgeneralstore.com/prodimages/67094-DEFAULT-L.jpg",
    inStock: true,
  },
  {
    name: "Hershey's Kisses",
    category: "Chocolate",
    price: 0.25,
    img: "https://www.ohnuts.com/noapp/showImage.cfm/zoom/4_MG_83691.jpg",
    inStock: true,
  },
  {
    name: "Crunch",
    category: "Chocolate",
    price: 1.5,
    img: "https://www.nicepng.com/png/detail/113-1132132_jolly-rancher-chews-original.png",
    inStock: true,
  },
  {
    name: "Kit-Kats",
    category: "Chocolate",
    price: 2,
    img: "https://www.nicepng.com/png/detail/113-1132132_jolly-rancher-chews-original.png",
    inStock: true,
  },
  {
    name: "Starburst",
    category: "Chewy",
    price: 2,
    img: "https://www.nicepng.com/png/detail/113-1132132_jolly-rancher-chews-original.png",
    inStock: true,
  },
];

export { candy };
